# Generated by Django 3.1.4 on 2021-01-17 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Liseli'), (1, 'Üniversiteli'), (2, 'Mezun')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='uni_image/default', null=True, upload_to='uni_image')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('history', models.TextField(max_length=500)),
                ('types', models.CharField(choices=[('feepaying', 'Özel Okul'), ('public', 'Devlet Okulu')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_info', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.university')),
            ],
        ),
        migrations.CreateModel(
            name='Unitable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.enrolee')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.university')),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edu_field', models.CharField(choices=[('mf', 'Sayısal'), ('tm', 'Eşit Ağırlık'), ('söz', 'Sözel'), ('dil', 'Dil')], default=None, max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.university')),
            ],
            options={
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('enrolee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.enrolee')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.university')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_year', models.CharField(choices=[('tdegree', 'İki Yıllık'), ('fdegree', 'Dört Yıllık')], max_length=100)),
                ('scholarship', models.IntegerField(choices=[(0, '%100 Burslu'), (1, '%75 Burslu'), (2, '%50 Burslu'), (3, '%25 Burslu')], default=3, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.faculties')),
            ],
            options={
                'unique_together': {('scholarship', 'name')},
            },
        ),
    ]
