# Generated by Django 3.1.4 on 2021-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='scholarship',
            field=models.IntegerField(choices=[(None, 'Ücretsiz'), (0, '%100 Burslu'), (1, '%75 Burslu'), (2, '%50 Burslu'), (3, '%25 Burslu')], default=3, null=True),
        ),
    ]
