# Generated by Django 3.1.4 on 2021-01-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210117_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='scholarship',
            field=models.CharField(choices=[(0, '%100 Burslu'), (1, '%75 Burslu'), (2, '%50 Burslu'), (3, '%25 Burslu'), (None, 'Ücretsiz')], default=None, max_length=10, null=True),
        ),
    ]
