# Generated by Django 3.1.4 on 2021-01-17 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210117_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(0)]),
        ),
    ]
